name: Pronto

on:
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin master --depth=1
      - uses: adwerx/pronto-ruby@main # use a tag version here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
