name: Pronto

on:
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin main --depth=1
      - uses: adwerx/pronto-ruby@main
        with:
          target: origin/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}