name: Pronto
on: [pull_request_target]

jobs:
  pronto:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Setup pronto
        run: gem install pronto pronto-rubocop
      - name: Run Pronto
        run: PRONTO_GITHUB_ACCESS_TOKEN="${{ github.token }}" pronto run -f github_combined_status -c origin/main -r rubocop