name: Pronto
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pronto:
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Setup pronto
        run: gem install pronto pronto-rubocop
      - name: Run Pronto
        env:
          ACTIONS_RUNNER_DEBUG: true 
        run: pronto run -f github_status -c origin/main -r rubocop
        